import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/context/CartContext"
import NavBar from '@/components/Navbar/NavBar'

const cabin_sketch = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-repeat" style={{backgroundImage: `url(/imgs/bgTexture.png)`}}>
      <CartContextProvider>
        <body className={cabin_sketch.className}>
          <NavBar/>
          {children}
        </body>
      </CartContextProvider>
    </html>
  );
}
