import type { Metadata } from "next";
import { Truculenta } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/context/CartContext"

const truculenta = Truculenta({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartContextProvider>
        <body className={truculenta.className}>{children}</body>
      </CartContextProvider>
    </html>
  );
}
